# ****************************************************************
#                              DEPENDENCIES
# ****************************************************************
# conda environment files
conda_env:
   bedops: env/bedops.yaml  # bedops
   gatk: env/gatk.yaml      # gatk

# number of threads to use, whenever possible
threads: 4  

# ****************************************************************
#                              INPUT
# ****************************************************************


# fastq files, adapters and genome files
# ----------------------------------------------------------------
input:
   fastq: input/fastq/                                          # raw fastq files
   genome:
      fasta: output/1_snpeff_database/genomes/P.falciparum.fa   # local copy of genome fasta file
      gff: output/1_snpeff_database/P.falciparum/genes.gff      # local copy of genome gff file
      regions: input/2_genome_reference/genome.bed.gz           # bed file with regions of interest
      url: https://plasmodb.org/common/downloads/release-51/Pfalciparum3D7/fasta/data/PlasmoDB-51_Pfalciparum3D7_Genome.fasta  # url to download genome fasta file



# ****************************************************************
#                              OUTPUT
# ****************************************************************


# copy genomes files to output directory
# ----------------------------------------------------------------
get_genome_data:
   dir_fasta: output/2_genome_reference/fasta/       # output directory
   fasta: output/2_genome_reference/fasta/genome.fa  # genome fasta file, copied from snpeff database
   gff: output/2_genome_reference/gff/genome.gff     # genome gff file, copied from snpeff database



# samtools_index - index genome fasta file
# ----------------------------------------------------------------
samtools_index:
   fasta_idx: output/2_genome_reference/fasta/genome.fa.fai  # genome fasta index file



# bedtools - convert genome GFF to BED
# ----------------------------------------------------------------
bedops_gff2bed:
   bed: output/2_genome_reference/bed/genome.bed  # genome bed file
   feature: protein_coding_gene                   # features to filter genome gff file, for read mapping
   conda_env: env/bedops.yaml                     # conda environment file



# trimmomatic - clip illumina adapters, paired end mode
# ----------------------------------------------------------------
trimmomatic:
   dir: output/3_trimmed_fastq/  # output directory
   trimmer:                      # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
      - "LEADING:3"
      - "TRAILING:3"
      - "SLIDINGWINDOW:4:15"
      - "MINLEN:36"
   extra:                        # extra options to pass to trimmomatic
      - "-threads 4"

# ----------------------------------------------------------------
#                             read mapping
# ----------------------------------------------------------------

# bwa - map reads to genome
# ----------------------------------------------------------------
bwa:
   index: output/2_genome_reference/index/genome  # genome fasta file
   dir: output/4_mapped_reads/1_bwa/              # output directory
   log: output/4_mapped_reads/1_bwa/log/          # log file


gatk:
   dir_clean_sam: output/4_mapped_reads/2_gatk_clean_sam/          # output directory
   dir_clean_sam_log: output/4_mapped_reads/2_gatk_clean_sam/log/  # output directory

# # create_genome_index - generate index files for genome mapping
# # ----------------------------------------------------------------
# bwa:
#    dir: output/4_aligned_bam/                             # output directory
#    read_group:
#       library: 1                                          # read group library
#       platform: illumina                                  # read group platform
#    genome_index: output/4_aligned_bam/genomeIndex/genome  # genome index prefix
#    mapping_qual: 60                                       # minimum mapping quality
#    exclude_flag: "0x104"                                  # exclude unnmapped and secondary alignments reads (i.e 0x4 + 0x100)



# # mapping_qual_stats - get mapping qual statistics
# # ----------------------------------------------------------------
# mapping_stats:                         
#    dir: output/5_map_qual_stats/  # output directory



# # variant calling - call variants against reference genome
# # ----------------------------------------------------------------
# bcftools:
#    dir: output/6_vcf_files/  # output directory
#    min_base_qual: 20         # minimum base quality



# # annotate_variants - annotate variants in vcf file
# # ----------------------------------------------------------------
# snpEff:
#    config: .snpEff.config         # snpEff config file
#    database: P.falciparum         # snpEff database name
#    dir: output/7_vcfs_annotated/  # output directory



# # extract_variants - extract variants from vcf file
# # ----------------------------------------------------------------
# snpSift:
#    dir: output/8_extracted_variants/  # output directory
