# ****************************************************************
#                              DEPENDENCIES
# ****************************************************************


# conda environment files
conda_env:
   bedops: env/bedops.yaml      # bedops
   bwa: env/bwa.yaml            # bwa
   gatk: env/gatk.yaml          # gatk
   samtools: env/samtools.yaml  # samtools



# number of threads to use, whenever possible
threads: 4  



# ****************************************************************
#                              INPUT
# ****************************************************************


# fastq files, adapters and genome files
# ----------------------------------------------------------------
input:
   fastq: input/fastq/                                          # raw fastq files
   genome:
      fasta: output/1_snpeff_database/genomes/P.falciparum.fa   # local copy of genome fasta file
      gff: output/1_snpeff_database/P.falciparum/genes.gff      # local copy of genome gff file
      regions: input/2_genome_reference/genome.bed.gz           # bed file with regions of interest
      url: https://plasmodb.org/common/downloads/release-51/Pfalciparum3D7/fasta/data/PlasmoDB-51_Pfalciparum3D7_Genome.fasta  # url to download genome fasta file



# ****************************************************************
#                              OUTPUT
# ****************************************************************


# copy genomes files to output directory
# ----------------------------------------------------------------
gather_genome_data:
   dir_fasta: output/2_genome_reference/fasta/        # output directory
   fasta: output/2_genome_reference/fasta/genome.fa   # genome fasta file, copied from snpeff database
   gff: output/2_genome_reference/gff/genome.gff      # genome gff file, copied from snpeff database
   core: input/bed/Pf3D7_core_genome.bed              # bed file with core genome regions
   dict: output/2_genome_reference/fasta/genome.dict  # genome dict file, generated from genome fasta file



# samtools_index - index genome fasta file
# ----------------------------------------------------------------
samtools_index:
   fasta_idx: output/2_genome_reference/fasta/genome.fa.fai  # genome fasta index file



# bedtools - convert genome GFF to BED
# ----------------------------------------------------------------
bedops_gff2bed:
   bed: output/2_genome_reference/bed/genome.bed  # genome bed file
   feature: protein_coding_gene                   # features to filter genome gff file, for read mapping
   conda_env: env/bedops.yaml                     # conda environment file



# trimmomatic - clip illumina adapters, paired end mode
# ----------------------------------------------------------------
trimmomatic:
   dir: output/3_trimmed_fastq/  # output directory
   trimmer:                      # See trimmomatic manual for adding additional options
      - "LEADING:3"
      - "TRAILING:3"
      - "SLIDINGWINDOW:4:15"
      - "MINLEN:36"
   extra:                        # extra options to pass to trimmomatic
      - "-threads 4"


# ----------------------------------------------------------------
#                             read mapping
# ----------------------------------------------------------------


# bwa_mem
# ----------------------------------------------------------------
bwa:
   index: output/2_genome_reference/index/genome  # genome fasta file
   dir: output/4_mapped_reads/1_bwa/              # output directory
   log: output/4_mapped_reads/1_bwa/log/          # log file


# gatk_clean_sam
# ----------------------------------------------------------------
gatk_clean:
   dir: output/4_mapped_reads/2_gatk_clean/      # output directory



# gatk_sort_sam
# ----------------------------------------------------------------
gatk_sort:
   dir: output/4_mapped_reads/3_gatk_sort/       # output directory



# gatk_markdup
# ----------------------------------------------------------------
gatk_markdup:
   dir: output/4_mapped_reads/4_gatk_markdup/              # output directory
   metrics: output/4_mapped_reads/4_gatk_markdup/metrics/  # output directory
   log: output/4_mapped_reads/4_gatk_markdup/log/          # output directory



# samtools_view
# ----------------------------------------------------------------
samtools_view:
   dir: output/4_mapped_reads/5_samtools/      # output directory
   log: output/4_mapped_reads/5_samtools/log/  # output directory



# samtools_idxstats & samtools_flagstat
# ----------------------------------------------------------------
samtools_stats:                         
   dir: output/4_mapped_reads/6_map_qual_stats/  # output directory



# gatk_collect_insert_size_metrics
# ----------------------------------------------------------------
gatk_insert_size:
   dir_metrics: output/4_mapped_reads/7_insert_size/metrics      # output directory
   dir_histogram: output/4_mapped_reads/7_insert_size/histogram  # output directory
   log: output/4_mapped_reads/7_insert_size/log                  # log files
   extra:                                                        # extra options to pass to gatk
      - "--MINIMUM_PCT 0.05"



# ######################################################################
#                        step 4 - variant calling
# ######################################################################


# gatk_java_opts - memory allocation for gatk tools
# ----------------------------------------------------------------
gatk_java_opts:   # replace '4' with the amaount of memory you want to use
   - "--java-options '-Xmx4g -Xms4g'"     # maximum heap size  



# gatk_haplotypecaller
# ----------------------------------------------------------------
gatk_haplotypecaller:
   dir: output/5_variants/1_gatk_haplotypecaller/      # output directory
   log: output/5_variants/1_gatk_haplotypecaller/log/  # output directory
   extra:
      - "--emit-ref-confidence GVCF"
      - "--sample-ploidy 2"
      - "--assembly-region-padding 100"
      - "--max-num-haplotypes-in-population 128"
      - "--kmer-size 10"
      - "--kmer-size 25"
      - "--min-dangling-branch-length 4"
      - "--heterozygosity 0.001"
      - "--indel-heterozygosity 1.25E-4"
      - "--min-assembly-region-size 50"
      - "--min-base-quality-score 10"
      - "--disable-read-filter null"
      - "--base-quality-score-threshold 12"



# gatk_genomics_db_import
# ----------------------------------------------------------------
gatk_genomicsdbimport:
   dir: output/5_variants/2_gatk_genomicsdbimport/genomicsdb  # output directory
   extra:
      # - "--sample-name-map list.tsv"          # optional - uncomment and replace list.tsv. See gatk manual for details
      - "--batch-size 0"
      - "--genomicsdb-segment-size 1048576"
      - "--genomicsdb-vcf-buffer-size 16384"



# gatk_genotype_gvcfs
# ----------------------------------------------------------------
gatk_genotype_gvcfs:
   dir: output/5_variants/3_gatk_genotypeVCFs/  # output directory
   extra:
      - "--genomicsdb-use-bcf-codec false"
      - "-stand-call-conf 30.0"
      - "--max-genotype-count 1024"