# number of threads to use, whenever possible
# ----------------------------------------------------------------
threads: 4  # number of threads to use, whenever possible



# choose filtering method to use for gatk
# ----------------------------------------------------------------
gatk_filtering_method: "hard"  # default to hard filtering {options: hard, soft}



# gatk_java_opts - memory allocation for gatk tools
# ----------------------------------------------------------------
gatk_java_opts:                   
  general:                        # ram and threads for less memory intensive gatk tools
    - "-Xms4G"                       # initial heap size
    - "-Xmx4G"                       # maximum heap size
    - "-XX:ParallelGCThreads=2"      # number of threads to use for garbage collection
  markduplicatesspark:            # https://hpc.nih.gov/training/gatk_tutorial/markdup.html#benchmarks-of-markduplicatesspark
    - "-Xms4G"                       # optimal mem=60G
    - "-Xmx4G"                       # optimal mem=60G
    - "-XX:ParallelGCThreads=2"      # optimal threads=16
  haplotypecaller:                # https://hpc.nih.gov/training/gatk_tutorial/haplotype-caller.html#benchmarks
    - "-Xms4G"                       # optimal mem=20G
    - "-Xmx4G"                       # optimal mem=20G
    - "-XX:ParallelGCThreads=2"      # optimal threads=2
  genomicsdb_import:              # https://hpc.nih.gov/training/gatk_tutorial/genomics-db-import.html#benchmarks-1
    - "-Xms4G"                       # optimal mem=2G
    - "-Xmx4G"                       # optimal mem=2G
    - "-XX:ParallelGCThreads=2"      # optimal threads=2
  genotype_gvcfs:                 # https://hpc.nih.gov/training/gatk_tutorial/genotype-gvcfs.html#benchmarks-2
    - "-Xms4G"                       # optimal mem=2G
    - "-Xmx4G"                       # optimal mem=2G    
    - "-XX:ParallelGCThreads=2"      # optimal threads=2
  vqsr:                           # https://hpc.nih.gov/training/gatk_tutorial/vqsr.html#benchmarks-of-variantrecalibrator
    - "-Xms4G"                       # optimal mem=4G
    - "-Xmx4G"                       # optimal mem=4G
    - "-XX:ParallelGCThreads=2"      # optimal threads=2
  applyvqsr:                      # https://hpc.nih.gov/training/gatk_tutorial/vqsr.html#benchmarks-of-applyvqsr
    - "-Xms4G"                       # optimal mem=6G
    - "-Xmx4G"                       # optimal mem=6G
    - "-XX:ParallelGCThreads=2"      # optimal threads=2



# fastq files, adapters (if needed) and genome files
# ----------------------------------------------------------------
input:
  fastq: input/fastq/                                        # raw fastq files
  genome:
    fasta: output/1_snpeff_database/genomes/P.falciparum.fa  # local copy of genome fasta file
    gff: output/1_snpeff_database/P.falciparum/genes.gff     # local copy of genome gff file
    bed: input/bed/p.falciparum_core_genome.bed              # bed file with core genome regions (10.12688/wellcomeopenres.14571.1))
    url: https://plasmodb.org/common/downloads/release-51/Pfalciparum3D7/fasta/data/PlasmoDB-51_Pfalciparum3D7_Genome.fasta  # url to download genome fasta file



# ################################################################
#                     Step 2 - Gather Genome Data
# ################################################################


# copy genomes files to output directory
# ----------------------------------------------------------------
genome_data:
  dir: output/2_genome_reference/  # output directory
  fasta: fasta/genome.fa           # genome fasta file, copied from snpeff database
  gff: gff/genome.gff              # genome gff file, copied from snpeff database
  dict: fasta/genome.dict          # genome dict file, generated from genome fasta file



# samtools_index - index genome fasta file
# ----------------------------------------------------------------
samtools_index:
  fasta_idx: output/2_genome_reference/fasta/genome.fa.fai  # genome fasta index file



# bedtools - convert genome GFF to BED
# ----------------------------------------------------------------
bedops_gff2bed:
  bed: output/2_genome_reference/bed/genome.bed  # genome bed file
  feature: protein_coding_gene                   # genome features to filter, e.g. {CDS, exon, mRNA, protein_coding_gene}



# ################################################################
#                   Step 3 - Fastq Quality Control
# ################################################################


# trimmomatic/fastp - clip illumina adapters, paired end mode
# ----------------------------------------------------------------
trim_reads:
  dir: output/3_trimmed_fastq/          # output directory
  trimmer: "Fastp"                      # trimmer to use, options: {Trimmomatic, Fastp}
  extra_trimmomatic:                    # See trimmomatic manual for adding additional options
    - "LEADING:3"                          # trim bases from the start of a read, if below a threshold quality {default: 3}             
    - "TRAILING:3"                         # trim bases from the end of a read, if below a threshold quality {default: 3}
    - "SLIDINGWINDOW:4:15"                 # scan the read with a 4-base wide sliding window, cutting when the average quality per base drops below 15 {default: 4:15}
    - "MINLEN:36"                          # drop the read if it is below this length {default: 36}
  extra_fastp:                          # See fastp manual for adding additional options
    - "--detect_adapter_for_pe"            # detect adapter automatically
    - "--cut_tail"                         # cut the read by quality from the end
    - "--cut_tail_mean_quality 20"         # the mean quality requirement option for cut_tail {default: 20}                               
    - "--cut_tail_window_size 4"           # the window size option of cut_tail {default: 4}                             
    - "--qualified_quality_phred 15"       # the quality value that a base is qualified {default: 15}
    - "--length_required 15"               # read length required to remain {default: 15}
    - "--length_limit 0"                   # if read length is longer than length_limit, it will be cut to length_limit {default: 0}



# ################################################################
#                    Step 4 - Map Reads to Genome
# ################################################################


# bwa_mem
# ----------------------------------------------------------------
bwa:
  index: output/2_genome_reference/index/genome  # genome fasta file
  dir: output/4_mapped_reads/a_bam_clean/        # output directory
  extra_bwa:                                     # extra options to pass to bwa
    - "-M"                                          # mark shorter split hits as secondary (for Picard compatibility)
  extra_fixmate:                                 # extra options to pass to samtools fixmate
    - "-m"                                          # Add mate score tag



# gatk_markdup
# ----------------------------------------------------------------
mark_duplicates:
  tool: MarkDuplicatesSpark                              # options: {MarkDuplicatesSpark, Samblaster}
  dir: output/4_mapped_reads/b_bam_markdup/              # output directory
  metrics: output/4_mapped_reads/b_bam_markdup/metrics/  # metrics directory
  extra_gatk:                                            # extra options to pass to gatk
    - "--remove-sequencing-duplicates"                      # remove optical/sequencing duplicates
    - "--create-output-bam-index true"                      # create output bam index
  extra_samblaster:                                      # extra options to pass to samblaster
    - "--removeDups"                                        # remove duplicates
    - "--addMateTags"                                       # add MC and MQ tags to all output paired-end SAM lines



# ######################################################################
#                      Step 5 - Mapping Quality Stats
# ######################################################################


# samtools_idxstats & samtools_flagstat
# ----------------------------------------------------------------
map_qual_stats:                         
  dir: output/4_mapped_reads/c_bam_mapping_stats/  # output directory
  extra_gatk:                                      # extra options to pass to gatk
    - "--MINIMUM_PCT 0.05"                            # minimum percentage of reads to include in stats {default: 0.05}



# ######################################################################
#                        Step 6 - Variant Calling
# ######################################################################


# gatk_haplotypecaller
# ----------------------------------------------------------------
gatk_haplotypecaller:
  dir: output/5_variant_calling/a_gatk_haplotypecaller/  # output directory
  extra:                                                 # extra options to pass to gatk
    - "--emit-ref-confidence GVCF"                          # mode for emitting reference confidence scores, possible values: {NONE, BP_RESOLUTION, GVCF}
    - "--sample-ploidy 2"                                   # ploidy (no# of chromosomes per sample), for pooled data, set to number of samples in each pool * ploidy) {Default value: 2}
    - "--assembly-region-padding 100"                       # amount of padding (in bp) to add to each side of the active region {Default value: 100}
    - "--min-assembly-region-size 100"                      # minimum size of an assembly region {Default value: 50}
    - "--max-num-haplotypes-in-population 128"              # maximum number of haplotypes in population {Default value: 128}
    - "--kmer-size 10"                                      # kmer size to use in the read threading assembler {Default value: 10}
    - "--kmer-size 25"                                      # kmer size to use in the read threading assembler {Default value: 25}
    - "--min-dangling-branch-length 4"                      # minimum length of a dangling branch to try to recover {Default value: 4}
    - "--heterozygosity 0.0029"                             # heterozygosity for SNP and indel calling {Default value: 0.001}
    - "--indel-heterozygosity 0.0017"                       # heterozygosity for indel calling {Default value: 1.25E-4}
    - "--disable-read-filter null"                          # read filters to be disabled before analysis
    - "--min-base-quality-score 10"                         # minimum base quality required to consider a base for calling {Default value: 10}
    - "--base-quality-score-threshold 18"                   # base qualities below this threshold will be reduced to the minimum {Default value: 18}



# gatk_genomics_db_import
# ----------------------------------------------------------------
vcf_sample_name_map:
  tsv: output/5_variant_calling/b_gatk_genomicsdb/sample_map/sample_name_map.txt  # output directory



gatk_genomicsdb:
  dir: output/5_variant_calling/b_gatk_genomicsdb/genomicsdb  # output directory
  extra:                                                      # extra options to pass to gatk
      - "--batch-size 0"                                        # number of samples for which readers are open at once. provides a way to minimize memory consumption {Default value: 0}
      - "--genomicsdb-segment-size 1048576"                     # segment size for writing to disk {Default value: 1048576}
      - "--genomicsdb-vcf-buffer-size 16384"                    # buffer size for writing to disk {Default value: 16384}



# gatk_genotype_gvcfs
# ----------------------------------------------------------------
gatk_genotype_gvcfs:
  dir: output/5_variant_calling/c_gatk_genotypeVCFs/            # output directory
  extra:                                                        # extra options to pass to gatk
    - "--genomicsdb-use-bcf-codec false"                          # use BCF codec for GenomicsDB, instead of default VCFCodec {Default value: false}
    - "--standard-min-confidence-threshold-for-calling 30.0"      # minimum phred-scaled confidence threshold for variant-calling {Default value: 30.0}
    - "--max-genotype-count 1024"                                 # maximum number of genotypes to consider at any site {Default value: 1024}



# ######################################################################
#                       Step 7 - Variant Filtering
# ######################################################################


# bcftools_normalize
# ----------------------------------------------------------------
bcftools:
  dir: output/6_variant_filtering/a_bcftools_normalize_vcf/  # output directory
  extra:                                                     # extra options to pass to bcftools
    normalize:
      - "--multiallelics -any"                                 # split multiallelic sites into biallelic records (-) or join biallelic sites into multiallelic records (+) {optios: snps|indels|both|any}                                         # reference sequence file
      - "--check-ref warn"                                     # option for incorrect or missing REF allele is encountered: exit (e), warn (w), exclude (x), or set/fix (s) bad sites
    annotate:
      - "--remove 'ID'"                                        # remove the existing ID field for each variant in the input VCF file
      - "--set-id +'%CHROM:%POS:%POS:%REF:%ALT'"               # set new ID field for each variant in the input VCF file
    view:
      - "-i 'AC>0'"                                            # select sites with at least one alternate allele, excluding reference-only calls (i.e., no variation)



# gatk_split_variants
# ----------------------------------------------------------------
gatk_var_split:
  dir: output/6_variant_filtering/b_gatk_variants_filter_hard/  # output directory



# gatk_variant_filtration, explained:
# - https://gatk.broadinstitute.org/hc/en-us/articles/360035890471-Hard-filtering-germline-short-variants
# - https://gatk.broadinstitute.org/hc/en-us/articles/360035531112--How-to-Filter-variants-either-with-VQSR-or-by-hard-filtering
# ----------------------------------------------------------------
gatk_filter_hard:
  dir: output/6_variant_filtering/b_gatk_variants_filter_hard/            # output directory
  extra_snps:                                                             # hard filters for SNPs
    - '-filter "DP < 1" --filter-name "DP1"'                                # DP = total depth of reads
    - '-filter "QD < 2.0" --filter-name "QD2"'                              # QD = variant confidence / depth
    - '-filter "QUAL < 30.0" --filter-name "QUAL30"'                        # QUAL = phred-scaled quality score
    - '-filter "SOR > 3.0" --filter-name "SOR3"'                            # SOR = strand bias
    - '-filter "FS > 60.0" --filter-name "FS60"'                            # FS = phred-scaled p-value using Fisher's exact test to detect strand bias
    - '-filter "MQ < 40.0" --filter-name "MQ40"'                            # MQ = RMS mapping quality
    - '-filter "MQRankSum < -12.5" --filter-name "MQRankSum-12.5"'          # MQRankSum = Z-score from Wilcoxon rank sum test of Alt vs. Ref read mapping qualities
    - '-filter "ReadPosRankSum < -8.0" --filter-name "ReadPosRankSum-8"'    # ReadPosRankSum = Z-score from Wilcoxon rank sum test of Alt vs. Ref read position bias
  extra_indels:                                                           # hard filters for indels, see above for explanation
    - '-filter "DP < 1" --filter-name "DP1"'
    - '-filter "QD < 2.0" --filter-name "QD2"'
    - '-filter "QUAL < 30.0" --filter-name "QUAL30"'
    - '-filter "FS > 200.0" --filter-name "FS200"'
    - '-filter "ReadPosRankSum < -20.0" --filter-name "ReadPosRankSum-20"'



# gatk_filter_soft
# ----------------------------------------------------------------
gatk_filter_soft:
  dir: output/6_variant_filtering/b_gatk_variants_filter_soft/      # output directory
  resource: 'brown,known=true,training=true,truth=true,prior=15.0'  # resource for VQSR
  sites: input/known_sites/strains.2kb.vcf.gz                       # known sites for VQSR
  extra:
    indels_vqsr:                              # variant quality score recalibration (vqsr) for indels
      - '--mode INDEL'                          # recalibration mode to employ
      - '--max-gaussians 4'                     # max number of Gaussians for the positive model {default: 8}
      - '--trust-all-polymorphic'               # trust that the input VCF contains only polymorphic sites
      - '--use-annotation QD'                   # names of the annotations to be used for calculations
      - '--use-annotation DP'
      - '--use-annotation FS'
      - '--use-annotation SOR'
      - '--use-annotation MQ'
    indels_apply_vsqr:                        # apply variant quality score recalibration (vqsr) to indels
      - '--mode INDEL'                          # recalibration mode to employ
      - '--exclude-filtered false'              # exclude filtered loci after applying the recalibration {default: false}
      - '--lod-score-cutoff -2.0'               # the VQSLOD score below which to start filtering {default: null}
      - '--create-output-variant-index true'    # create a VCF index when writing a VCF file {default: false}
    snps_vqsr:                                  # variant quality score recalibration (vqsr) for snps
      - '--mode SNP'                            # recalibration mode to employ
      - '--max-gaussians 4'                     # max number of Gaussians for the positive model {default: 8}
      - '--trust-all-polymorphic'               # trust that the input VCF contains only polymorphic sites
      - '--use-annotation QD'                   # names of the annotations to be used for calculations
      - '--use-annotation DP'
      - '--use-annotation FS'
      - '--use-annotation SOR'
      - '--use-annotation MQ'
    snps_apply_vsqr:                          # apply variant quality score recalibration (vqsr) to snps
      - '--mode SNP'                            # recalibration mode to employ
      - '--exclude-filtered false'              # exclude filtered loci after applying the recalibration {default: false}
      - '--lod-score-cutoff 0.0'                # the VQSLOD score below which to start filtering {default: null}
      - '--create-output-variant-index true'    # create a VCF index when writing a VCF file {default: false}



# gatk_merge_vcfs
# ----------------------------------------------------------------
gatk_merge_vcfs:
  dir: output/6_variant_filtering/c_gatk_variants_merged/  # output directory



# gatk_filter_pass
# ----------------------------------------------------------------
gatk_filter_pass:
  dir: output/6_variant_filtering/c_gatk_variants_merged/  # output directory
  extra:
    - '--exclude-filtered true'  # exclude filtered loci that are marked as filtered by previous steps {default: false}



# ######################################################################
#                      Step 8 - Variant Annotation
# ######################################################################


# snpeff_annotate_variants
# ----------------------------------------------------------------
snpeff:
  dir: output/7_variant_annotation/  # output directory
  config: .snpEff.config             # snpeff config file
  database: P.falciparum             # snpeff database
  extra_snpeff:                      # extra options to pass to snpeff
    - "-hgvs1LetterAa"                  # use one-letter amino acid codes in HGVS
    - "-noStats"                        # do not create stats (summary) file
    - "-hgvsOld"                        # use old HGVS format