# ################################################################
#                        ADDTITONAL RESOURCES
# ################################################################


# number of threads to use, whenever possible
# ----------------------------------------------------------------
threads: 4  # replace '4' with the number of threads you want to use



# gatk_java_opts - memory allocation for gatk tools
# ----------------------------------------------------------------
gatk_java_opts:       # replace '4' with the amaount of memory you want to use
   - "-Xmx4g -Xms4g"  # maximum heap size


# fastq files, adapters (if needed) and genome files
# ----------------------------------------------------------------
input:
   fastq: input/fastq/                                                   # raw fastq files
   genome:
      fasta: output/1_snpeff_database/genomes/P.falciparum.fa            # local copy of genome fasta file
      gff: output/1_snpeff_database/P.falciparum/genes.gff               # local copy of genome gff file
      core: input/bed/Pf3D7_core_genome.bed                              # bed file with core genome regions
      url: https://plasmodb.org/common/downloads/release-51/Pfalciparum3D7/fasta/data/PlasmoDB-51_Pfalciparum3D7_Genome.fasta  # url to download genome fasta file



# ################################################################
#                     step 2 - gather genome data
# ################################################################


# copy genomes files to output directory
# ----------------------------------------------------------------
gather_genome_data:
   dir_fasta: output/2_genome_reference/fasta/        # output directory
   fasta: output/2_genome_reference/fasta/genome.fa   # genome fasta file, copied from snpeff database
   gff: output/2_genome_reference/gff/genome.gff      # genome gff file, copied from snpeff database
   dict: output/2_genome_reference/fasta/genome.dict  # genome dict file, generated from genome fasta file



# samtools_index - index genome fasta file
# ----------------------------------------------------------------
samtools_index:
   fasta_idx: output/2_genome_reference/fasta/genome.fa.fai  # genome fasta index file



# bedtools - convert genome GFF to BED
# ----------------------------------------------------------------
bedops_gff2bed:
   bed: output/2_genome_reference/bed/genome.bed  # genome bed file
   feature: protein_coding_gene                   # features to filter genome gff file, for read mapping
   conda_env: env/bedops.yaml                     # conda environment file



# ################################################################
#                      step 3 - quality control
# ################################################################


# trimmomatic - clip illumina adapters, paired end mode
# ----------------------------------------------------------------
trimmomatic:
   dir: output/3_trimmed_fastq/  # output directory
   trimmer:                      # See trimmomatic manual for adding additional options
      - "LEADING:3"
      - "TRAILING:3"
      - "SLIDINGWINDOW:4:15"
      - "MINLEN:36"



# ################################################################
#                    step 4 - map reads to genome
# ################################################################


# bwa_mem
# ----------------------------------------------------------------
bwa:
   index: output/2_genome_reference/index/genome  # genome fasta file
   dir: output/4_mapped_reads/1_bwa/              # output directory
   log: output/4_mapped_reads/1_bwa/log/          # log directory



# gatk_clean
# ----------------------------------------------------------------
gatk_clean:
   dir: output/4_mapped_reads/2_gatk_clean/      # output directory



# gatk_markdup
# ----------------------------------------------------------------
gatk_markdup:
   dir: output/4_mapped_reads/3_gatk_markdup/              # output directory
   metrics: output/4_mapped_reads/3_gatk_markdup/metrics/  # metrics directory
   log: output/4_mapped_reads/3_gatk_markdup/log/          # log directory
   extra:
      - "--remove-all-duplicates true"
      - "--create-output-bam-index true"



# samtools_view
# ----------------------------------------------------------------
samtools_view:
   dir: output/4_mapped_reads/4_samtools/      # output directory
   log: output/4_mapped_reads/4_samtools/log/  # log directory



# samtools_idxstats & samtools_flagstat
# ----------------------------------------------------------------
samtools_stats:                         
   dir: output/4_mapped_reads/5_map_qual_stats/  # output directory



# gatk_collect_insert_size_metrics
# ----------------------------------------------------------------
gatk_insert_size:
   dir_metrics: output/4_mapped_reads/7_insert_size/metrics      # output directory
   dir_histogram: output/4_mapped_reads/7_insert_size/histogram  # output directory
   log: output/4_mapped_reads/7_insert_size/log                  # log files
   extra:                                                        # extra options to pass to gatk
      - "--MINIMUM_PCT 0.05"



# ######################################################################
#                        step 5 - variant calling
# ######################################################################


# gatk_haplotypecaller
# ----------------------------------------------------------------
gatk_haplotypecaller:
   dir: output/5_variant_calling/1_gatk_haplotypecaller/      # output directory
   log: output/5_variant_calling/1_gatk_haplotypecaller/log/  # output directory
   erc: GVCF                                                  # Possible values: {NONE, BP_RESOLUTION, GVCF}
   extra:                                                     # extra options to pass to gatk
      - "--emit-ref-confidence GVCF"
      - "--sample-ploidy 2"
      - "--assembly-region-padding 100"
      - "--max-num-haplotypes-in-population 128"
      - "--kmer-size 10"
      - "--kmer-size 25"
      - "--min-dangling-branch-length 4"
      - "--heterozygosity 0.001"
      - "--indel-heterozygosity 1.25E-4"
      - "--min-assembly-region-size 50"
      - "--min-base-quality-score 10"
      - "--disable-read-filter null"
      - "--base-quality-score-threshold 12"



# gatk_genomics_db_import
# ----------------------------------------------------------------
vcf_sample_name_map:
   tsv: output/5_variant_calling/2_gatk_genomicsdb/1_sample_map/sample_name_map.txt  # output directory



gatk_genomicsdb:
   dir: output/5_variant_calling/2_gatk_genomicsdb/2_genomicsdb  # output directory
   extra:
      - "--batch-size 0"
      - "--genomicsdb-segment-size 1048576"
      - "--genomicsdb-vcf-buffer-size 16384"



# gatk_genotype_gvcfs
# ----------------------------------------------------------------
gatk_genotype_gvcfs:
   dir: output/5_variant_calling/3_gatk_genotypeVCFs/  # output directory
   extra:
      - "--genomicsdb-use-bcf-codec false"
      - "--standard-min-confidence-threshold-for-calling 30.0"
      - "--max-genotype-count 1024"



# ######################################################################
#                       step 6 - variant filtering
# ######################################################################


# gatk_variant_filtration
# ----------------------------------------------------------------
gatk_var_filter_hard:
   dir: output/6_variants/1_gatk_variant_filtration/     # output directory
   log: output/6_variants/1_gatk_variant_filtration/log  # log directory
   extra:
   -  '-filter "DP < 10" --filter-name "DP10"'
   -  '-filter "QD < 2.0" --filter-name "QD2"'
   -  '-filter "QUAL < 30.0" --filter-name "QUAL30"'
   -  '-filter "SOR > 3.0" --filter-name "SOR3"'
   -  '-filter "FS > 60.0" --filter-name "FS60"'
   -  '-filter "MQ < 40.0" --filter-name "MQ40"'
   -  '-filter "MQRankSum < -12.5" --filter-name "MQRankSum-12.5"'
   -  '-filter "ReadPosRankSum < -8.0" --filter-name "ReadPosRankSum-8"'