# number of threads to use, whenever possible
# ----------------------------------------------------------------
threads: 4  # replace '4' with the number of threads you want to use



# gatk_java_opts - memory allocation for gatk tools
# TODO: add initial memory allocation for gatk tools
# ----------------------------------------------------------------
gatk_java_opts:                 # replace '4' with the amaount of memory to use
   - "-Xms4G"                   # initial heap size
   - "-Xmx4G"                   # maximum heap size
   - "-XX:ParallelGCThreads=2"  # number of threads to use for garbage collection



# fastq files, adapters (if needed) and genome files
# ----------------------------------------------------------------
input:
   fastq: input/fastq/                                         # raw fastq files
   genome:
      fasta: output/1_snpeff_database/genomes/P.falciparum.fa  # local copy of genome fasta file
      gff: output/1_snpeff_database/P.falciparum/genes.gff     # local copy of genome gff file
      intervals: input/bed/p.falciparum_genes.bed              # bed file with core genome regions (10.12688/wellcomeopenres.14571.1))
      url: https://plasmodb.org/common/downloads/release-51/Pfalciparum3D7/fasta/data/PlasmoDB-51_Pfalciparum3D7_Genome.fasta  # url to download genome fasta file



# ################################################################
#                     Step 2 - Gather Genome Data
# ################################################################


# copy genomes files to output directory
# ----------------------------------------------------------------
gather_genome_data:
   dir_fasta: output/2_genome_reference/fasta/        # output directory
   fasta: output/2_genome_reference/fasta/genome.fa   # genome fasta file, copied from snpeff database
   gff: output/2_genome_reference/gff/genome.gff      # genome gff file, copied from snpeff database
   dict: output/2_genome_reference/fasta/genome.dict  # genome dict file, generated from genome fasta file



# samtools_index - index genome fasta file
# ----------------------------------------------------------------
samtools_index:
   fasta_idx: output/2_genome_reference/fasta/genome.fa.fai  # genome fasta index file



# bedtools - convert genome GFF to BED
# ----------------------------------------------------------------
bedops_gff2bed:
   bed: output/2_genome_reference/bed/genome.bed  # genome bed file
   feature: protein_coding_gene                   # features to filter genome gff file, for read mapping



# ################################################################
#                   Step 3 - Fastq Quality Control
# ################################################################


# trimmomatic/fastp - clip illumina adapters, paired end mode
# ----------------------------------------------------------------
trim_reads:
   dir: output/3_trimmed_fastq/     # output directory
   trimmer: "Fastp"                 # trimmer to use, options: {Trimmomatic, Fastp}
   extra_trimmomatic:               # See trimmomatic manual for adding additional options
      - "LEADING:3"                               
      - "TRAILING:3"
      - "SLIDINGWINDOW:4:15"
      - "MINLEN:36"
   extra_fastp:                     # See fastp manual for adding additional options
      - "--detect_adapter_for_pe"
      - "--cut_tail"
      - "--cut_tail_mean_quality 20"                               
      - "--cut_tail_window_size 4"                                 
      - "--qualified_quality_phred 15"
      - "--length_required 15"
      - "--length_limit 0"



# ################################################################
#                    Step 4 - Map Reads to Genome
# ################################################################


# bwa_mem
# ----------------------------------------------------------------
bwa:
   index: output/2_genome_reference/index/genome  # genome fasta file
   dir: output/4_mapped_reads/a_bam_clean/        # output directory
   extra_bwa:
      - "-M"
   extra_fixmate:
      - "-m"



# gatk_markdup
# ----------------------------------------------------------------
mark_duplicates:
   tool: MarkDuplicatesSpark                              # options: {MarkDuplicatesSpark, Samblaster}
   dir: output/4_mapped_reads/b_bam_markdup/              # output directory
   metrics: output/4_mapped_reads/b_bam_markdup/metrics/  # metrics directory
   extra_gatk:                                            # extra options to pass to gatk
      - "--remove-sequencing-duplicates"
      - "--create-output-bam-index true"
   extra_samblaster:                                      # extra options to pass to sambamba
      - "--removeDups"
      - "--addMateTags"



# ######################################################################
#                      Step 5 - Mapping Quality Stats
# ######################################################################


# samtools_idxstats & samtools_flagstat
# ----------------------------------------------------------------
map_qual_stats:                         
   dir: output/4_mapped_reads/c_bam_mapping_stats/  # output directory
   extra_gatk:                                      # extra options to pass to gatk
      - "--MINIMUM_PCT 0.05"



# ######################################################################
#                        Step 6 - Variant Calling
# ######################################################################


# gatk_haplotypecaller
# ----------------------------------------------------------------
gatk_haplotypecaller:
   dir: output/5_variant_calling/a_gatk_haplotypecaller/  # output directory
   extra:                                                 # extra options to pass to gatk
      - "--emit-ref-confidence GVCF"
      - "--sample-ploidy 2"
      - "--assembly-region-padding 100"
      - "--max-num-haplotypes-in-population 128"
      - "--kmer-size 10"
      - "--kmer-size 25"
      - "--min-dangling-branch-length 4"
      - "--heterozygosity 0.001"
      - "--indel-heterozygosity 1.25E-4"
      - "--min-assembly-region-size 50"
      - "--min-base-quality-score 10"
      - "--disable-read-filter null"
      - "--base-quality-score-threshold 12"



# gatk_genomics_db_import
# ----------------------------------------------------------------
vcf_sample_name_map:
   tsv: output/5_variant_calling/b_gatk_genomicsdb/sample_map/sample_name_map.txt  # output directory



gatk_genomicsdb:
   dir: output/5_variant_calling/b_gatk_genomicsdb/genomicsdb  # output directory
   extra:                                                      # extra options to pass to gatk
      - "--batch-size 0"
      - "--genomicsdb-segment-size 1048576"
      - "--genomicsdb-vcf-buffer-size 16384"



# gatk_genotype_gvcfs
# ----------------------------------------------------------------
gatk_genotype_gvcfs:
   dir: output/5_variant_calling/c_gatk_genotypeVCFs/  # output directory
   extra:                                              # extra options to pass to gatk
      - "--genomicsdb-use-bcf-codec false"
      - "--standard-min-confidence-threshold-for-calling 30.0"
      - "--max-genotype-count 1024"



# ######################################################################
#                       Step 7 - Variant Filtering
# ######################################################################


# gatk_variant_separate
# ----------------------------------------------------------------
gatk_var_split:
   dir: output/6_variant_filtering/a_gatk_variants_split/  # output directory



# gatk_variant_filtration, explained:
# - https://gatk.broadinstitute.org/hc/en-us/articles/360035890471-Hard-filtering-germline-short-variants
# - https://gatk.broadinstitute.org/hc/en-us/articles/360035531112--How-to-Filter-variants-either-with-VQSR-or-by-hard-filtering
# ----------------------------------------------------------------
gatk_filter_hard:
   dir: output/6_variant_filtering/b_gatk_variants_filtered/     # output directory
   extra_snps:                                                   # extra options to pass to gatk
   - '-filter "DP < 1" --filter-name "DP1"'
   - '-filter "QD < 2.0" --filter-name "QD2"'
   - '-filter "QUAL < 30.0" --filter-name "QUAL30"'
   - '-filter "SOR > 3.0" --filter-name "SOR3"'
   - '-filter "FS > 60.0" --filter-name "FS60"'
   - '-filter "MQ < 40.0" --filter-name "MQ40"'
   - '-filter "MQRankSum < -12.5" --filter-name "MQRankSum-12.5"'
   - '-filter "ReadPosRankSum < -8.0" --filter-name "ReadPosRankSum-8"'
   extra_indels:                                                # extra options to pass to gatk
   - '-filter "DP < 1" --filter-name "DP1"'
   - '-filter "QD < 2.0" --filter-name "QD2"'
   - '-filter "QUAL < 30.0" --filter-name "QUAL30"'
   - '-filter "FS > 200.0" --filter-name "FS200"'
   - '-filter "ReadPosRankSum < -20.0" --filter-name "ReadPosRankSum-20"'



# gatk_variant_filtration
# ----------------------------------------------------------------
gatk_merge_vcfs:
   dir: output/6_variant_filtering/c_gatk_variants_merged/  # output directory



# gatk_filter_pass
# ----------------------------------------------------------------
gatk_filter_pass:
   dir: output/6_variant_filtering/d_gatk_variants_pass/  # output directory



# ######################################################################
#                      Step 8 - Variant Annotation
# ######################################################################


# snpeff_annotate_variants
# ----------------------------------------------------------------
snpeff:
   dir: output/7_variant_annotation/  # output directory
   config: .snpEff.config             # snpeff config file
   database: P.falciparum             # snpeff database
   extra_snpeff:                      # extra options to pass to snpeff
      - "-no-downstream"                   # do not annotate downstream variants
      - "-no-intergenic"                 # do not annotate intergenic variants
      - "-no-intron"                     # do not annotate intronic variants
      - "-no-upstream"                   # do not annotate upstream variants
      - "-no-utr"                        # do not annotate UTR variants
      - "-no SPLICE_SITE_REGION"         # do not annotate splice site variants
      - "-hgvs1LetterAa"                 # use one-letter amino acid codes in HGVS
      - "-noLof"                         # do not annotate loss-of-function variants
      - "-noShiftHgvs"                   # do not annotate HGVS for shifted variants
      - "-noMotif"                       # do not annotate regulatory features
      - "-noInteraction"                 # do not annotate protein-protein interactions
      - "-noStats"                       # do not annotate varian                          
